import Head from 'next/head';
import '../node_modules/normalize.css';
import { MainContainer, Container, Center, DarkDiv } from '../styles/Home';
import { HomeLinks, SocialIcons, Intro } from './../components';
import { GiYinYang } from 'react-icons/gi';
import { useContext, useState } from 'react';
import { LanguageContext } from '../pages/_app';

export default function Home() {
  const [lang] = useContext(LanguageContext);
  const [click, setClick] = useState(0);

  const Text = {
    he: {
      clickMe: 'מה אתה לוחץ עלי?',
    },
    en: {
      clickMe: 'Click Me',
    },
  };

  return (
    <div>
      <Head>
        <title>Yosefus Flavius</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <Container>
          <HomeLinks click={click} />
          <SocialIcons click={click} />
          <DarkDiv click={click} />
          {click ? <Intro click={click} /> : null}
          <Center click={click} onClick={() => setClick(click == 0 ? 1 : 0)}>
            <h3>
              <GiYinYang />
            </h3>
            <span>{Text[lang].clickMe}</span>
          </Center>
        </Container>
      </MainContainer>
    </div>
  );
}
