import Head from 'next/head';
import styles from '../styles/Home.module.css';
import '../node_modules/normalize.css';
import { MainContainer, Container } from '../styles/Home';
import { Logo, PowerButton } from './../components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yosefus Flavius</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <Container>
          {/* <PowerButton /> */}
          {/* <Logo /> */}
        </Container>
      </MainContainer>
    </div>
  );
}
